/**
 * Indonesia provinces and regencies/cities, for the checkout address form.
 * Sourced from BPS/Kemendagri administrative codes (emsifa/api-wilayah-indonesia,
 * a static mirror of the same public dataset). Bundled rather than fetched: this
 * data changes on the order of once a decade, and a static list means the
 * dropdown works with zero network round-trips and no API key.
 *
 * Uses the pre-2022 34-province structure — the six Papua provinces created in
 * 2022-2023 are not yet broken out in this source and still resolve to the
 * original Papua / Papua Barat. Courier postal infrastructure has not fully
 * caught up to the new provinces either, so this does not block shipping.
 */

export type Region = { id: string; name: string };

export const PROVINCES: Region[] = [
  { id: "11", name: "Aceh" },
  { id: "51", name: "Bali" },
  { id: "36", name: "Banten" },
  { id: "17", name: "Bengkulu" },
  { id: "34", name: "DI Yogyakarta" },
  { id: "31", name: "DKI Jakarta" },
  { id: "75", name: "Gorontalo" },
  { id: "15", name: "Jambi" },
  { id: "32", name: "Jawa Barat" },
  { id: "33", name: "Jawa Tengah" },
  { id: "35", name: "Jawa Timur" },
  { id: "61", name: "Kalimantan Barat" },
  { id: "63", name: "Kalimantan Selatan" },
  { id: "62", name: "Kalimantan Tengah" },
  { id: "64", name: "Kalimantan Timur" },
  { id: "65", name: "Kalimantan Utara" },
  { id: "19", name: "Kepulauan Bangka Belitung" },
  { id: "21", name: "Kepulauan Riau" },
  { id: "18", name: "Lampung" },
  { id: "81", name: "Maluku" },
  { id: "82", name: "Maluku Utara" },
  { id: "52", name: "Nusa Tenggara Barat" },
  { id: "53", name: "Nusa Tenggara Timur" },
  { id: "94", name: "Papua" },
  { id: "91", name: "Papua Barat" },
  { id: "14", name: "Riau" },
  { id: "76", name: "Sulawesi Barat" },
  { id: "73", name: "Sulawesi Selatan" },
  { id: "72", name: "Sulawesi Tengah" },
  { id: "74", name: "Sulawesi Tenggara" },
  { id: "71", name: "Sulawesi Utara" },
  { id: "13", name: "Sumatera Barat" },
  { id: "16", name: "Sumatera Selatan" },
  { id: "12", name: "Sumatera Utara" },
];

export const REGENCIES_BY_PROVINCE: Record<string, Region[]> = {
  "11": [
    { id: "1107", name: "Kabupaten Aceh Barat" },
    { id: "1112", name: "Kabupaten Aceh Barat Daya" },
    { id: "1108", name: "Kabupaten Aceh Besar" },
    { id: "1116", name: "Kabupaten Aceh Jaya" },
    { id: "1103", name: "Kabupaten Aceh Selatan" },
    { id: "1102", name: "Kabupaten Aceh Singkil" },
    { id: "1114", name: "Kabupaten Aceh Tamiang" },
    { id: "1106", name: "Kabupaten Aceh Tengah" },
    { id: "1104", name: "Kabupaten Aceh Tenggara" },
    { id: "1105", name: "Kabupaten Aceh Timur" },
    { id: "1111", name: "Kabupaten Aceh Utara" },
    { id: "1117", name: "Kabupaten Bener Meriah" },
    { id: "1110", name: "Kabupaten Bireuen" },
    { id: "1113", name: "Kabupaten Gayo Lues" },
    { id: "1115", name: "Kabupaten Nagan Raya" },
    { id: "1109", name: "Kabupaten Pidie" },
    { id: "1118", name: "Kabupaten Pidie Jaya" },
    { id: "1101", name: "Kabupaten Simeulue" },
    { id: "1171", name: "Kota Banda Aceh" },
    { id: "1173", name: "Kota Langsa" },
    { id: "1174", name: "Kota Lhokseumawe" },
    { id: "1172", name: "Kota Sabang" },
    { id: "1175", name: "Kota Subulussalam" },
  ],
  "12": [
    { id: "1208", name: "Kabupaten Asahan" },
    { id: "1219", name: "Kabupaten Batu Bara" },
    { id: "1210", name: "Kabupaten Dairi" },
    { id: "1212", name: "Kabupaten Deli Serdang" },
    { id: "1215", name: "Kabupaten Humbang Hasundutan" },
    { id: "1211", name: "Kabupaten Karo" },
    { id: "1207", name: "Kabupaten Labuhan Batu" },
    { id: "1222", name: "Kabupaten Labuhan Batu Selatan" },
    { id: "1223", name: "Kabupaten Labuhan Batu Utara" },
    { id: "1213", name: "Kabupaten Langkat" },
    { id: "1202", name: "Kabupaten Mandailing Natal" },
    { id: "1201", name: "Kabupaten Nias" },
    { id: "1225", name: "Kabupaten Nias Barat" },
    { id: "1214", name: "Kabupaten Nias Selatan" },
    { id: "1224", name: "Kabupaten Nias Utara" },
    { id: "1221", name: "Kabupaten Padang Lawas" },
    { id: "1220", name: "Kabupaten Padang Lawas Utara" },
    { id: "1216", name: "Kabupaten Pakpak Bharat" },
    { id: "1217", name: "Kabupaten Samosir" },
    { id: "1218", name: "Kabupaten Serdang Bedagai" },
    { id: "1209", name: "Kabupaten Simalungun" },
    { id: "1203", name: "Kabupaten Tapanuli Selatan" },
    { id: "1204", name: "Kabupaten Tapanuli Tengah" },
    { id: "1205", name: "Kabupaten Tapanuli Utara" },
    { id: "1206", name: "Kabupaten Toba Samosir" },
    { id: "1276", name: "Kota Binjai" },
    { id: "1278", name: "Kota Gunungsitoli" },
    { id: "1275", name: "Kota Medan" },
    { id: "1277", name: "Kota Padangsidimpuan" },
    { id: "1273", name: "Kota Pematang Siantar" },
    { id: "1271", name: "Kota Sibolga" },
    { id: "1272", name: "Kota Tanjung Balai" },
    { id: "1274", name: "Kota Tebing Tinggi" },
  ],
  "13": [
    { id: "1307", name: "Kabupaten Agam" },
    { id: "1311", name: "Kabupaten Dharmasraya" },
    { id: "1301", name: "Kabupaten Kepulauan Mentawai" },
    { id: "1308", name: "Kabupaten Lima Puluh Kota" },
    { id: "1306", name: "Kabupaten Padang Pariaman" },
    { id: "1309", name: "Kabupaten Pasaman" },
    { id: "1312", name: "Kabupaten Pasaman Barat" },
    { id: "1302", name: "Kabupaten Pesisir Selatan" },
    { id: "1304", name: "Kabupaten Sijunjung" },
    { id: "1303", name: "Kabupaten Solok" },
    { id: "1310", name: "Kabupaten Solok Selatan" },
    { id: "1305", name: "Kabupaten Tanah Datar" },
    { id: "1375", name: "Kota Bukittinggi" },
    { id: "1371", name: "Kota Padang" },
    { id: "1374", name: "Kota Padang Panjang" },
    { id: "1377", name: "Kota Pariaman" },
    { id: "1376", name: "Kota Payakumbuh" },
    { id: "1373", name: "Kota Sawah Lunto" },
    { id: "1372", name: "Kota Solok" },
  ],
  "14": [
    { id: "1408", name: "Kabupaten Bengkalis" },
    { id: "1403", name: "Kabupaten Indragiri Hilir" },
    { id: "1402", name: "Kabupaten Indragiri Hulu" },
    { id: "1406", name: "Kabupaten Kampar" },
    { id: "1410", name: "Kabupaten Kepulauan Meranti" },
    { id: "1401", name: "Kabupaten Kuantan Singingi" },
    { id: "1404", name: "Kabupaten Pelalawan" },
    { id: "1409", name: "Kabupaten Rokan Hilir" },
    { id: "1407", name: "Kabupaten Rokan Hulu" },
    { id: "1405", name: "Kabupaten S I A K" },
    { id: "1473", name: "Kota D U M A I" },
    { id: "1471", name: "Kota Pekanbaru" },
  ],
  "15": [
    { id: "1504", name: "Kabupaten Batang Hari" },
    { id: "1509", name: "Kabupaten Bungo" },
    { id: "1501", name: "Kabupaten Kerinci" },
    { id: "1502", name: "Kabupaten Merangin" },
    { id: "1505", name: "Kabupaten Muaro Jambi" },
    { id: "1503", name: "Kabupaten Sarolangun" },
    { id: "1507", name: "Kabupaten Tanjung Jabung Barat" },
    { id: "1506", name: "Kabupaten Tanjung Jabung Timur" },
    { id: "1508", name: "Kabupaten Tebo" },
    { id: "1571", name: "Kota Jambi" },
    { id: "1572", name: "Kota Sungai Penuh" },
  ],
  "16": [
    { id: "1607", name: "Kabupaten Banyu Asin" },
    { id: "1611", name: "Kabupaten Empat Lawang" },
    { id: "1604", name: "Kabupaten Lahat" },
    { id: "1603", name: "Kabupaten Muara Enim" },
    { id: "1606", name: "Kabupaten Musi Banyuasin" },
    { id: "1605", name: "Kabupaten Musi Rawas" },
    { id: "1613", name: "Kabupaten Musi Rawas Utara" },
    { id: "1610", name: "Kabupaten Ogan Ilir" },
    { id: "1602", name: "Kabupaten Ogan Komering Ilir" },
    { id: "1601", name: "Kabupaten Ogan Komering Ulu" },
    { id: "1608", name: "Kabupaten Ogan Komering Ulu Selatan" },
    { id: "1609", name: "Kabupaten Ogan Komering Ulu Timur" },
    { id: "1612", name: "Kabupaten Penukal Abab Lematang Ilir" },
    { id: "1674", name: "Kota Lubuklinggau" },
    { id: "1673", name: "Kota Pagar Alam" },
    { id: "1671", name: "Kota Palembang" },
    { id: "1672", name: "Kota Prabumulih" },
  ],
  "17": [
    { id: "1701", name: "Kabupaten Bengkulu Selatan" },
    { id: "1709", name: "Kabupaten Bengkulu Tengah" },
    { id: "1703", name: "Kabupaten Bengkulu Utara" },
    { id: "1704", name: "Kabupaten Kaur" },
    { id: "1708", name: "Kabupaten Kepahiang" },
    { id: "1707", name: "Kabupaten Lebong" },
    { id: "1706", name: "Kabupaten Mukomuko" },
    { id: "1702", name: "Kabupaten Rejang Lebong" },
    { id: "1705", name: "Kabupaten Seluma" },
    { id: "1771", name: "Kota Bengkulu" },
  ],
  "18": [
    { id: "1801", name: "Kabupaten Lampung Barat" },
    { id: "1803", name: "Kabupaten Lampung Selatan" },
    { id: "1805", name: "Kabupaten Lampung Tengah" },
    { id: "1804", name: "Kabupaten Lampung Timur" },
    { id: "1806", name: "Kabupaten Lampung Utara" },
    { id: "1811", name: "Kabupaten Mesuji" },
    { id: "1809", name: "Kabupaten Pesawaran" },
    { id: "1813", name: "Kabupaten Pesisir Barat" },
    { id: "1810", name: "Kabupaten Pringsewu" },
    { id: "1802", name: "Kabupaten Tanggamus" },
    { id: "1812", name: "Kabupaten Tulang Bawang Barat" },
    { id: "1808", name: "Kabupaten Tulangbawang" },
    { id: "1807", name: "Kabupaten Way Kanan" },
    { id: "1871", name: "Kota Bandar Lampung" },
    { id: "1872", name: "Kota Metro" },
  ],
  "19": [
    { id: "1901", name: "Kabupaten Bangka" },
    { id: "1903", name: "Kabupaten Bangka Barat" },
    { id: "1905", name: "Kabupaten Bangka Selatan" },
    { id: "1904", name: "Kabupaten Bangka Tengah" },
    { id: "1902", name: "Kabupaten Belitung" },
    { id: "1906", name: "Kabupaten Belitung Timur" },
    { id: "1971", name: "Kota Pangkal Pinang" },
  ],
  "21": [
    { id: "2102", name: "Kabupaten Bintan" },
    { id: "2101", name: "Kabupaten Karimun" },
    { id: "2105", name: "Kabupaten Kepulauan Anambas" },
    { id: "2104", name: "Kabupaten Lingga" },
    { id: "2103", name: "Kabupaten Natuna" },
    { id: "2171", name: "Kota B A T A M" },
    { id: "2172", name: "Kota Tanjung Pinang" },
  ],
  "31": [
    { id: "3101", name: "Kabupaten Kepulauan Seribu" },
    { id: "3174", name: "Kota Jakarta Barat" },
    { id: "3173", name: "Kota Jakarta Pusat" },
    { id: "3171", name: "Kota Jakarta Selatan" },
    { id: "3172", name: "Kota Jakarta Timur" },
    { id: "3175", name: "Kota Jakarta Utara" },
  ],
  "32": [
    { id: "3204", name: "Kabupaten Bandung" },
    { id: "3217", name: "Kabupaten Bandung Barat" },
    { id: "3216", name: "Kabupaten Bekasi" },
    { id: "3201", name: "Kabupaten Bogor" },
    { id: "3207", name: "Kabupaten Ciamis" },
    { id: "3203", name: "Kabupaten Cianjur" },
    { id: "3209", name: "Kabupaten Cirebon" },
    { id: "3205", name: "Kabupaten Garut" },
    { id: "3212", name: "Kabupaten Indramayu" },
    { id: "3215", name: "Kabupaten Karawang" },
    { id: "3208", name: "Kabupaten Kuningan" },
    { id: "3210", name: "Kabupaten Majalengka" },
    { id: "3218", name: "Kabupaten Pangandaran" },
    { id: "3214", name: "Kabupaten Purwakarta" },
    { id: "3213", name: "Kabupaten Subang" },
    { id: "3202", name: "Kabupaten Sukabumi" },
    { id: "3211", name: "Kabupaten Sumedang" },
    { id: "3206", name: "Kabupaten Tasikmalaya" },
    { id: "3273", name: "Kota Bandung" },
    { id: "3279", name: "Kota Banjar" },
    { id: "3275", name: "Kota Bekasi" },
    { id: "3271", name: "Kota Bogor" },
    { id: "3277", name: "Kota Cimahi" },
    { id: "3274", name: "Kota Cirebon" },
    { id: "3276", name: "Kota Depok" },
    { id: "3272", name: "Kota Sukabumi" },
    { id: "3278", name: "Kota Tasikmalaya" },
  ],
  "33": [
    { id: "3304", name: "Kabupaten Banjarnegara" },
    { id: "3302", name: "Kabupaten Banyumas" },
    { id: "3325", name: "Kabupaten Batang" },
    { id: "3316", name: "Kabupaten Blora" },
    { id: "3309", name: "Kabupaten Boyolali" },
    { id: "3329", name: "Kabupaten Brebes" },
    { id: "3301", name: "Kabupaten Cilacap" },
    { id: "3321", name: "Kabupaten Demak" },
    { id: "3315", name: "Kabupaten Grobogan" },
    { id: "3320", name: "Kabupaten Jepara" },
    { id: "3313", name: "Kabupaten Karanganyar" },
    { id: "3305", name: "Kabupaten Kebumen" },
    { id: "3324", name: "Kabupaten Kendal" },
    { id: "3310", name: "Kabupaten Klaten" },
    { id: "3319", name: "Kabupaten Kudus" },
    { id: "3308", name: "Kabupaten Magelang" },
    { id: "3318", name: "Kabupaten Pati" },
    { id: "3326", name: "Kabupaten Pekalongan" },
    { id: "3327", name: "Kabupaten Pemalang" },
    { id: "3303", name: "Kabupaten Purbalingga" },
    { id: "3306", name: "Kabupaten Purworejo" },
    { id: "3317", name: "Kabupaten Rembang" },
    { id: "3322", name: "Kabupaten Semarang" },
    { id: "3314", name: "Kabupaten Sragen" },
    { id: "3311", name: "Kabupaten Sukoharjo" },
    { id: "3328", name: "Kabupaten Tegal" },
    { id: "3323", name: "Kabupaten Temanggung" },
    { id: "3312", name: "Kabupaten Wonogiri" },
    { id: "3307", name: "Kabupaten Wonosobo" },
    { id: "3371", name: "Kota Magelang" },
    { id: "3375", name: "Kota Pekalongan" },
    { id: "3373", name: "Kota Salatiga" },
    { id: "3374", name: "Kota Semarang" },
    { id: "3372", name: "Kota Surakarta" },
    { id: "3376", name: "Kota Tegal" },
  ],
  "34": [
    { id: "3402", name: "Kabupaten Bantul" },
    { id: "3403", name: "Kabupaten Gunung Kidul" },
    { id: "3401", name: "Kabupaten Kulon Progo" },
    { id: "3404", name: "Kabupaten Sleman" },
    { id: "3471", name: "Kota Yogyakarta" },
  ],
  "35": [
    { id: "3526", name: "Kabupaten Bangkalan" },
    { id: "3510", name: "Kabupaten Banyuwangi" },
    { id: "3505", name: "Kabupaten Blitar" },
    { id: "3522", name: "Kabupaten Bojonegoro" },
    { id: "3511", name: "Kabupaten Bondowoso" },
    { id: "3525", name: "Kabupaten Gresik" },
    { id: "3509", name: "Kabupaten Jember" },
    { id: "3517", name: "Kabupaten Jombang" },
    { id: "3506", name: "Kabupaten Kediri" },
    { id: "3524", name: "Kabupaten Lamongan" },
    { id: "3508", name: "Kabupaten Lumajang" },
    { id: "3519", name: "Kabupaten Madiun" },
    { id: "3520", name: "Kabupaten Magetan" },
    { id: "3507", name: "Kabupaten Malang" },
    { id: "3516", name: "Kabupaten Mojokerto" },
    { id: "3518", name: "Kabupaten Nganjuk" },
    { id: "3521", name: "Kabupaten Ngawi" },
    { id: "3501", name: "Kabupaten Pacitan" },
    { id: "3528", name: "Kabupaten Pamekasan" },
    { id: "3514", name: "Kabupaten Pasuruan" },
    { id: "3502", name: "Kabupaten Ponorogo" },
    { id: "3513", name: "Kabupaten Probolinggo" },
    { id: "3527", name: "Kabupaten Sampang" },
    { id: "3515", name: "Kabupaten Sidoarjo" },
    { id: "3512", name: "Kabupaten Situbondo" },
    { id: "3529", name: "Kabupaten Sumenep" },
    { id: "3503", name: "Kabupaten Trenggalek" },
    { id: "3523", name: "Kabupaten Tuban" },
    { id: "3504", name: "Kabupaten Tulungagung" },
    { id: "3579", name: "Kota Batu" },
    { id: "3572", name: "Kota Blitar" },
    { id: "3571", name: "Kota Kediri" },
    { id: "3577", name: "Kota Madiun" },
    { id: "3573", name: "Kota Malang" },
    { id: "3576", name: "Kota Mojokerto" },
    { id: "3575", name: "Kota Pasuruan" },
    { id: "3574", name: "Kota Probolinggo" },
    { id: "3578", name: "Kota Surabaya" },
  ],
  "36": [
    { id: "3602", name: "Kabupaten Lebak" },
    { id: "3601", name: "Kabupaten Pandeglang" },
    { id: "3604", name: "Kabupaten Serang" },
    { id: "3603", name: "Kabupaten Tangerang" },
    { id: "3672", name: "Kota Cilegon" },
    { id: "3673", name: "Kota Serang" },
    { id: "3671", name: "Kota Tangerang" },
    { id: "3674", name: "Kota Tangerang Selatan" },
  ],
  "51": [
    { id: "5103", name: "Kabupaten Badung" },
    { id: "5106", name: "Kabupaten Bangli" },
    { id: "5108", name: "Kabupaten Buleleng" },
    { id: "5104", name: "Kabupaten Gianyar" },
    { id: "5101", name: "Kabupaten Jembrana" },
    { id: "5107", name: "Kabupaten Karang Asem" },
    { id: "5105", name: "Kabupaten Klungkung" },
    { id: "5102", name: "Kabupaten Tabanan" },
    { id: "5171", name: "Kota Denpasar" },
  ],
  "52": [
    { id: "5206", name: "Kabupaten Bima" },
    { id: "5205", name: "Kabupaten Dompu" },
    { id: "5201", name: "Kabupaten Lombok Barat" },
    { id: "5202", name: "Kabupaten Lombok Tengah" },
    { id: "5203", name: "Kabupaten Lombok Timur" },
    { id: "5208", name: "Kabupaten Lombok Utara" },
    { id: "5204", name: "Kabupaten Sumbawa" },
    { id: "5207", name: "Kabupaten Sumbawa Barat" },
    { id: "5272", name: "Kota Bima" },
    { id: "5271", name: "Kota Mataram" },
  ],
  "53": [
    { id: "5307", name: "Kabupaten Alor" },
    { id: "5306", name: "Kabupaten Belu" },
    { id: "5311", name: "Kabupaten Ende" },
    { id: "5309", name: "Kabupaten Flores Timur" },
    { id: "5303", name: "Kabupaten Kupang" },
    { id: "5308", name: "Kabupaten Lembata" },
    { id: "5321", name: "Kabupaten Malaka" },
    { id: "5313", name: "Kabupaten Manggarai" },
    { id: "5315", name: "Kabupaten Manggarai Barat" },
    { id: "5319", name: "Kabupaten Manggarai Timur" },
    { id: "5318", name: "Kabupaten Nagekeo" },
    { id: "5312", name: "Kabupaten Ngada" },
    { id: "5314", name: "Kabupaten Rote Ndao" },
    { id: "5320", name: "Kabupaten Sabu Raijua" },
    { id: "5310", name: "Kabupaten Sikka" },
    { id: "5301", name: "Kabupaten Sumba Barat" },
    { id: "5317", name: "Kabupaten Sumba Barat Daya" },
    { id: "5316", name: "Kabupaten Sumba Tengah" },
    { id: "5302", name: "Kabupaten Sumba Timur" },
    { id: "5304", name: "Kabupaten Timor Tengah Selatan" },
    { id: "5305", name: "Kabupaten Timor Tengah Utara" },
    { id: "5371", name: "Kota Kupang" },
  ],
  "61": [
    { id: "6102", name: "Kabupaten Bengkayang" },
    { id: "6108", name: "Kabupaten Kapuas Hulu" },
    { id: "6111", name: "Kabupaten Kayong Utara" },
    { id: "6106", name: "Kabupaten Ketapang" },
    { id: "6112", name: "Kabupaten Kubu Raya" },
    { id: "6103", name: "Kabupaten Landak" },
    { id: "6110", name: "Kabupaten Melawi" },
    { id: "6104", name: "Kabupaten Mempawah" },
    { id: "6101", name: "Kabupaten Sambas" },
    { id: "6105", name: "Kabupaten Sanggau" },
    { id: "6109", name: "Kabupaten Sekadau" },
    { id: "6107", name: "Kabupaten Sintang" },
    { id: "6171", name: "Kota Pontianak" },
    { id: "6172", name: "Kota Singkawang" },
  ],
  "62": [
    { id: "6204", name: "Kabupaten Barito Selatan" },
    { id: "6212", name: "Kabupaten Barito Timur" },
    { id: "6205", name: "Kabupaten Barito Utara" },
    { id: "6211", name: "Kabupaten Gunung Mas" },
    { id: "6203", name: "Kabupaten Kapuas" },
    { id: "6209", name: "Kabupaten Katingan" },
    { id: "6201", name: "Kabupaten Kotawaringin Barat" },
    { id: "6202", name: "Kabupaten Kotawaringin Timur" },
    { id: "6207", name: "Kabupaten Lamandau" },
    { id: "6213", name: "Kabupaten Murung Raya" },
    { id: "6210", name: "Kabupaten Pulang Pisau" },
    { id: "6208", name: "Kabupaten Seruyan" },
    { id: "6206", name: "Kabupaten Sukamara" },
    { id: "6271", name: "Kota Palangka Raya" },
  ],
  "63": [
    { id: "6311", name: "Kabupaten Balangan" },
    { id: "6303", name: "Kabupaten Banjar" },
    { id: "6304", name: "Kabupaten Barito Kuala" },
    { id: "6306", name: "Kabupaten Hulu Sungai Selatan" },
    { id: "6307", name: "Kabupaten Hulu Sungai Tengah" },
    { id: "6308", name: "Kabupaten Hulu Sungai Utara" },
    { id: "6302", name: "Kabupaten Kota Baru" },
    { id: "6309", name: "Kabupaten Tabalong" },
    { id: "6310", name: "Kabupaten Tanah Bumbu" },
    { id: "6301", name: "Kabupaten Tanah Laut" },
    { id: "6305", name: "Kabupaten Tapin" },
    { id: "6372", name: "Kota Banjar Baru" },
    { id: "6371", name: "Kota Banjarmasin" },
  ],
  "64": [
    { id: "6405", name: "Kabupaten Berau" },
    { id: "6402", name: "Kabupaten Kutai Barat" },
    { id: "6403", name: "Kabupaten Kutai Kartanegara" },
    { id: "6404", name: "Kabupaten Kutai Timur" },
    { id: "6411", name: "Kabupaten Mahakam Hulu" },
    { id: "6401", name: "Kabupaten Paser" },
    { id: "6409", name: "Kabupaten Penajam Paser Utara" },
    { id: "6471", name: "Kota Balikpapan" },
    { id: "6474", name: "Kota Bontang" },
    { id: "6472", name: "Kota Samarinda" },
  ],
  "65": [
    { id: "6502", name: "Kabupaten Bulungan" },
    { id: "6501", name: "Kabupaten Malinau" },
    { id: "6504", name: "Kabupaten Nunukan" },
    { id: "6503", name: "Kabupaten Tana Tidung" },
    { id: "6571", name: "Kota Tarakan" },
  ],
  "71": [
    { id: "7101", name: "Kabupaten Bolaang Mongondow" },
    { id: "7110", name: "Kabupaten Bolaang Mongondow Selatan" },
    { id: "7111", name: "Kabupaten Bolaang Mongondow Timur" },
    { id: "7107", name: "Kabupaten Bolaang Mongondow Utara" },
    { id: "7103", name: "Kabupaten Kepulauan Sangihe" },
    { id: "7104", name: "Kabupaten Kepulauan Talaud" },
    { id: "7102", name: "Kabupaten Minahasa" },
    { id: "7105", name: "Kabupaten Minahasa Selatan" },
    { id: "7109", name: "Kabupaten Minahasa Tenggara" },
    { id: "7106", name: "Kabupaten Minahasa Utara" },
    { id: "7108", name: "Kabupaten Siau Tagulandang Biaro" },
    { id: "7172", name: "Kota Bitung" },
    { id: "7174", name: "Kota Kotamobagu" },
    { id: "7171", name: "Kota Manado" },
    { id: "7173", name: "Kota Tomohon" },
  ],
  "72": [
    { id: "7202", name: "Kabupaten Banggai" },
    { id: "7201", name: "Kabupaten Banggai Kepulauan" },
    { id: "7211", name: "Kabupaten Banggai Laut" },
    { id: "7207", name: "Kabupaten Buol" },
    { id: "7205", name: "Kabupaten Donggala" },
    { id: "7203", name: "Kabupaten Morowali" },
    { id: "7212", name: "Kabupaten Morowali Utara" },
    { id: "7208", name: "Kabupaten Parigi Moutong" },
    { id: "7204", name: "Kabupaten Poso" },
    { id: "7210", name: "Kabupaten Sigi" },
    { id: "7209", name: "Kabupaten Tojo Una-una" },
    { id: "7206", name: "Kabupaten Toli-toli" },
    { id: "7271", name: "Kota Palu" },
  ],
  "73": [
    { id: "7303", name: "Kabupaten Bantaeng" },
    { id: "7310", name: "Kabupaten Barru" },
    { id: "7311", name: "Kabupaten Bone" },
    { id: "7302", name: "Kabupaten Bulukumba" },
    { id: "7316", name: "Kabupaten Enrekang" },
    { id: "7306", name: "Kabupaten Gowa" },
    { id: "7304", name: "Kabupaten Jeneponto" },
    { id: "7301", name: "Kabupaten Kepulauan Selayar" },
    { id: "7317", name: "Kabupaten Luwu" },
    { id: "7325", name: "Kabupaten Luwu Timur" },
    { id: "7322", name: "Kabupaten Luwu Utara" },
    { id: "7308", name: "Kabupaten Maros" },
    { id: "7309", name: "Kabupaten Pangkajene Dan Kepulauan" },
    { id: "7315", name: "Kabupaten Pinrang" },
    { id: "7314", name: "Kabupaten Sidenreng Rappang" },
    { id: "7307", name: "Kabupaten Sinjai" },
    { id: "7312", name: "Kabupaten Soppeng" },
    { id: "7305", name: "Kabupaten Takalar" },
    { id: "7318", name: "Kabupaten Tana Toraja" },
    { id: "7326", name: "Kabupaten Toraja Utara" },
    { id: "7313", name: "Kabupaten Wajo" },
    { id: "7371", name: "Kota Makassar" },
    { id: "7373", name: "Kota Palopo" },
    { id: "7372", name: "Kota Parepare" },
  ],
  "74": [
    { id: "7406", name: "Kabupaten Bombana" },
    { id: "7401", name: "Kabupaten Buton" },
    { id: "7415", name: "Kabupaten Buton Selatan" },
    { id: "7414", name: "Kabupaten Buton Tengah" },
    { id: "7409", name: "Kabupaten Buton Utara" },
    { id: "7404", name: "Kabupaten Kolaka" },
    { id: "7411", name: "Kabupaten Kolaka Timur" },
    { id: "7408", name: "Kabupaten Kolaka Utara" },
    { id: "7403", name: "Kabupaten Konawe" },
    { id: "7412", name: "Kabupaten Konawe Kepulauan" },
    { id: "7405", name: "Kabupaten Konawe Selatan" },
    { id: "7410", name: "Kabupaten Konawe Utara" },
    { id: "7402", name: "Kabupaten Muna" },
    { id: "7413", name: "Kabupaten Muna Barat" },
    { id: "7407", name: "Kabupaten Wakatobi" },
    { id: "7472", name: "Kota Baubau" },
    { id: "7471", name: "Kota Kendari" },
  ],
  "75": [
    { id: "7501", name: "Kabupaten Boalemo" },
    { id: "7504", name: "Kabupaten Bone Bolango" },
    { id: "7502", name: "Kabupaten Gorontalo" },
    { id: "7505", name: "Kabupaten Gorontalo Utara" },
    { id: "7503", name: "Kabupaten Pohuwato" },
    { id: "7571", name: "Kota Gorontalo" },
  ],
  "76": [
    { id: "7601", name: "Kabupaten Majene" },
    { id: "7603", name: "Kabupaten Mamasa" },
    { id: "7604", name: "Kabupaten Mamuju" },
    { id: "7606", name: "Kabupaten Mamuju Tengah" },
    { id: "7605", name: "Kabupaten Mamuju Utara" },
    { id: "7602", name: "Kabupaten Polewali Mandar" },
  ],
  "81": [
    { id: "8104", name: "Kabupaten Buru" },
    { id: "8109", name: "Kabupaten Buru Selatan" },
    { id: "8105", name: "Kabupaten Kepulauan Aru" },
    { id: "8108", name: "Kabupaten Maluku Barat Daya" },
    { id: "8103", name: "Kabupaten Maluku Tengah" },
    { id: "8102", name: "Kabupaten Maluku Tenggara" },
    { id: "8101", name: "Kabupaten Maluku Tenggara Barat" },
    { id: "8106", name: "Kabupaten Seram Bagian Barat" },
    { id: "8107", name: "Kabupaten Seram Bagian Timur" },
    { id: "8171", name: "Kota Ambon" },
    { id: "8172", name: "Kota Tual" },
  ],
  "82": [
    { id: "8201", name: "Kabupaten Halmahera Barat" },
    { id: "8204", name: "Kabupaten Halmahera Selatan" },
    { id: "8202", name: "Kabupaten Halmahera Tengah" },
    { id: "8206", name: "Kabupaten Halmahera Timur" },
    { id: "8205", name: "Kabupaten Halmahera Utara" },
    { id: "8203", name: "Kabupaten Kepulauan Sula" },
    { id: "8207", name: "Kabupaten Pulau Morotai" },
    { id: "8208", name: "Kabupaten Pulau Taliabu" },
    { id: "8271", name: "Kota Ternate" },
    { id: "8272", name: "Kota Tidore Kepulauan" },
  ],
  "91": [
    { id: "9101", name: "Kabupaten Fakfak" },
    { id: "9102", name: "Kabupaten Kaimana" },
    { id: "9105", name: "Kabupaten Manokwari" },
    { id: "9111", name: "Kabupaten Manokwari Selatan" },
    { id: "9110", name: "Kabupaten Maybrat" },
    { id: "9112", name: "Kabupaten Pegunungan Arfak" },
    { id: "9108", name: "Kabupaten Raja Ampat" },
    { id: "9107", name: "Kabupaten Sorong" },
    { id: "9106", name: "Kabupaten Sorong Selatan" },
    { id: "9109", name: "Kabupaten Tambrauw" },
    { id: "9104", name: "Kabupaten Teluk Bintuni" },
    { id: "9103", name: "Kabupaten Teluk Wondama" },
    { id: "9171", name: "Kota Sorong" },
  ],
  "94": [
    { id: "9415", name: "Kabupaten Asmat" },
    { id: "9409", name: "Kabupaten Biak Numfor" },
    { id: "9413", name: "Kabupaten Boven Digoel" },
    { id: "9436", name: "Kabupaten Deiyai" },
    { id: "9434", name: "Kabupaten Dogiyai" },
    { id: "9435", name: "Kabupaten Intan Jaya" },
    { id: "9403", name: "Kabupaten Jayapura" },
    { id: "9402", name: "Kabupaten Jayawijaya" },
    { id: "9420", name: "Kabupaten Keerom" },
    { id: "9408", name: "Kabupaten Kepulauan Yapen" },
    { id: "9430", name: "Kabupaten Lanny Jaya" },
    { id: "9428", name: "Kabupaten Mamberamo Raya" },
    { id: "9431", name: "Kabupaten Mamberamo Tengah" },
    { id: "9414", name: "Kabupaten Mappi" },
    { id: "9401", name: "Kabupaten Merauke" },
    { id: "9412", name: "Kabupaten Mimika" },
    { id: "9404", name: "Kabupaten Nabire" },
    { id: "9429", name: "Kabupaten Nduga" },
    { id: "9410", name: "Kabupaten Paniai" },
    { id: "9417", name: "Kabupaten Pegunungan Bintang" },
    { id: "9433", name: "Kabupaten Puncak" },
    { id: "9411", name: "Kabupaten Puncak Jaya" },
    { id: "9419", name: "Kabupaten Sarmi" },
    { id: "9427", name: "Kabupaten Supiori" },
    { id: "9418", name: "Kabupaten Tolikara" },
    { id: "9426", name: "Kabupaten Waropen" },
    { id: "9416", name: "Kabupaten Yahukimo" },
    { id: "9432", name: "Kabupaten Yalimo" },
    { id: "9471", name: "Kota Jayapura" },
  ],
};
